---
- name: Copying files from controller to hosts
  hosts: planetexpress
  connection: ansible.builtin.ssh
  gather_facts: true # default is true

  tasks:

    - name: Copy Fry's resume to hosts
      ansible.builtin.copy:
        src: /workspaces/alta3training/ansible/criticalmodules/copy/files/fry.txt   # on the controller
        dest: ~/fry.txt      # home directory on hosts
